# Generated by Django 4.1.5 on 2023-02-03 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_users_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
