# Generated by Django 4.1.5 on 2023-02-20 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='posted_message',
            new_name='message',
        ),
    ]
